# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/acb610/Downloads/nexys4ddr_master_xdc/Nexys4DDR_Master.xdc

# Block Designs: bd/mb/mb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb || ORIG_REF_NAME==mb}]

# IP: bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_microblaze_0_0 || ORIG_REF_NAME==mb_microblaze_0_0}]

# IP: bd/mb/ip/mb_dlmb_v10_0/mb_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_dlmb_v10_0 || ORIG_REF_NAME==mb_dlmb_v10_0}]

# IP: bd/mb/ip/mb_ilmb_v10_0/mb_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ilmb_v10_0 || ORIG_REF_NAME==mb_ilmb_v10_0}]

# IP: bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_dlmb_bram_if_cntlr_0}]

# IP: bd/mb/ip/mb_ilmb_bram_if_cntlr_0/mb_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ilmb_bram_if_cntlr_0}]

# IP: bd/mb/ip/mb_lmb_bram_0/mb_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_lmb_bram_0 || ORIG_REF_NAME==mb_lmb_bram_0}]

# IP: bd/mb/ip/mb_mdm_1_0/mb_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_mdm_1_0 || ORIG_REF_NAME==mb_mdm_1_0}]

# IP: bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_clk_wiz_1_0 || ORIG_REF_NAME==mb_clk_wiz_1_0}]

# IP: bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_axi_uartlite_0_0 || ORIG_REF_NAME==mb_axi_uartlite_0_0}]

# IP: bd/mb/ip/mb_microblaze_0_axi_periph_0/mb_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_microblaze_0_axi_periph_0}]

# XDC: bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_microblaze_0_0 || ORIG_REF_NAME==mb_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0_ooc.xdc

# XDC: bd/mb/ip/mb_dlmb_v10_0/mb_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_dlmb_v10_0 || ORIG_REF_NAME==mb_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb/ip/mb_dlmb_v10_0/mb_dlmb_v10_0_ooc.xdc

# XDC: bd/mb/ip/mb_ilmb_v10_0/mb_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_ilmb_v10_0 || ORIG_REF_NAME==mb_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb/ip/mb_ilmb_v10_0/mb_ilmb_v10_0_ooc.xdc

# XDC: bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb/ip/mb_ilmb_bram_if_cntlr_0/mb_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb/ip/mb_lmb_bram_0/mb_lmb_bram_0_ooc.xdc

# XDC: bd/mb/ip/mb_mdm_1_0/mb_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_mdm_1_0 || ORIG_REF_NAME==mb_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mb/ip/mb_mdm_1_0/mb_mdm_1_0_ooc_trace.xdc

# XDC: bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_clk_wiz_1_0 || ORIG_REF_NAME==mb_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_clk_wiz_1_0 || ORIG_REF_NAME==mb_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0_ooc.xdc

# XDC: bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_axi_uartlite_0_0 || ORIG_REF_NAME==mb_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_axi_uartlite_0_0 || ORIG_REF_NAME==mb_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb/mb_ooc.xdc
