# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.cache/wt [current_project]
set_property parent.project_path C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/mb.bd
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_microblaze_0_0/mb_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_dlmb_v10_0/mb_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_dlmb_v10_0/mb_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_ilmb_v10_0/mb_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_ilmb_v10_0/mb_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_dlmb_bram_if_cntlr_0/mb_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_ilmb_bram_if_cntlr_0/mb_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_lmb_bram_0/mb_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_mdm_1_0/mb_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_mdm_1_0/mb_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_clk_wiz_1_0/mb_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/ip/mb_axi_uartlite_0_0/mb_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/mb_ooc.xdc]
set_property is_locked true [get_files C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/mb.bd]

read_vhdl -library xil_defaultlib C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/mb_test/mb_test.srcs/sources_1/bd/mb/hdl/mb_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/acb610/Downloads/nexys4ddr_master_xdc/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/acb610/Downloads/nexys4ddr_master_xdc/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mb_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mb_wrapper.dcp

catch { report_utilization -file mb_wrapper_utilization_synth.rpt -pb mb_wrapper_utilization_synth.pb }
