webtalk_init -webtalk_dir C:\\Users\\acb610\\Documents\\GitHub\\CS2204-Summer-2016-Research-Project\\ppm-revamp\\Xilinx-Files\\test\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun 21 13:06:27 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ups3o8s3l2d2cv933i4o0a0uau" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1466528345102" -context "sdk\\\\hardware/1466528345102"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1466528345102"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1466528345102"
webtalk_add_data -client sdk -key VivadoVersion -value "" -context "sdk\\\\hardware/1466528345102"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1466528345102"
webtalk_add_data -client sdk -key Device -value "xc7a100t" -context "sdk\\\\hardware/1466528345102"
webtalk_add_data -client sdk -key IsHandoff -value "false" -context "sdk\\\\hardware/1466528345102"
webtalk_add_data -client sdk -key uid -value "1466528351877" -context "sdk\\\\bsp/1466528351877"
webtalk_add_data -client sdk -key hwid -value "1466528345102" -context "sdk\\\\bsp/1466528351877"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1466528351877"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1466528351877"
webtalk_add_data -client sdk -key uid -value "1466528444358" -context "sdk\\\\bsp/1466528444358"
webtalk_add_data -client sdk -key hwid -value "1466528345102" -context "sdk\\\\bsp/1466528444358"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1466528444358"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1466528444358"
webtalk_add_data -client sdk -key uid -value "1466528447964" -context "sdk\\\\application/1466528447964"
webtalk_add_data -client sdk -key hwid -value "1466528345102" -context "sdk\\\\application/1466528447964"
webtalk_add_data -client sdk -key bspid -value "1466528444358" -context "sdk\\\\application/1466528447964"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1466528447964"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1466528447964"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1466528447964"
webtalk_transmit -clientid 618692792 -regid "" -xml C:\\Users\\acb610\\Documents\\GitHub\\CS2204-Summer-2016-Research-Project\\ppm-revamp\\Xilinx-Files\\test\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\acb610\\Documents\\GitHub\\CS2204-Summer-2016-Research-Project\\ppm-revamp\\Xilinx-Files\\test\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\acb610\\Documents\\GitHub\\CS2204-Summer-2016-Research-Project\\ppm-revamp\\Xilinx-Files\\test\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
