# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/acb610/Downloads/nexys4ddr_master_xdc/Nexys4DDR_Master.xdc

# Block Designs: bd/microblaze/microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze || ORIG_REF_NAME==microblaze}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/microblaze_microblaze_mcs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_mcs_0_0 || ORIG_REF_NAME==microblaze_microblaze_mcs_0_0}]

# Block Designs: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/bd_6a9c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c || ORIG_REF_NAME==bd_6a9c}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_6a9c_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_microblaze_I_0 || ORIG_REF_NAME==bd_6a9c_microblaze_I_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_6a9c_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_rst_0_0 || ORIG_REF_NAME==bd_6a9c_rst_0_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_6a9c_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_ilmb_0 || ORIG_REF_NAME==bd_6a9c_ilmb_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_6a9c_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_dlmb_0 || ORIG_REF_NAME==bd_6a9c_dlmb_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_6a9c_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_dlmb_cntlr_0 || ORIG_REF_NAME==bd_6a9c_dlmb_cntlr_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_6a9c_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_ilmb_cntlr_0 || ORIG_REF_NAME==bd_6a9c_ilmb_cntlr_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_6a9c_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_lmb_bram_I_0 || ORIG_REF_NAME==bd_6a9c_lmb_bram_I_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_6a9c_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6a9c_iomodule_0_0 || ORIG_REF_NAME==bd_6a9c_iomodule_0_0}]

# IP: bd/microblaze/ip/microblaze_top_0_0/microblaze_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_top_0_0 || ORIG_REF_NAME==microblaze_top_0_0}]

# IP: bd/microblaze/ip/microblaze_xlslice_0_0/microblaze_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xlslice_0_0 || ORIG_REF_NAME==microblaze_xlslice_0_0}]

# IP: bd/microblaze/ip/microblaze_xlslice_1_1/microblaze_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xlslice_1_1 || ORIG_REF_NAME==microblaze_xlslice_1_1}]

# IP: bd/microblaze/ip/microblaze_xlslice_1_2/microblaze_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xlslice_1_2 || ORIG_REF_NAME==microblaze_xlslice_1_2}]

# IP: bd/microblaze/ip/microblaze_xlslice_1_3/microblaze_xlslice_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xlslice_1_3 || ORIG_REF_NAME==microblaze_xlslice_1_3}]

# IP: bd/microblaze/ip/microblaze_xlconcat_0_0/microblaze_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xlconcat_0_0 || ORIG_REF_NAME==microblaze_xlconcat_0_0}]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_6a9c_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6a9c_microblaze_I_0 || ORIG_REF_NAME==bd_6a9c_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_6a9c_microblaze_I_0_ooc_debug.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_6a9c_microblaze_I_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_6a9c_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6a9c_rst_0_0 || ORIG_REF_NAME==bd_6a9c_rst_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_6a9c_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6a9c_rst_0_0 || ORIG_REF_NAME==bd_6a9c_rst_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_6a9c_rst_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_6a9c_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6a9c_ilmb_0 || ORIG_REF_NAME==bd_6a9c_ilmb_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_6a9c_ilmb_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_6a9c_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6a9c_dlmb_0 || ORIG_REF_NAME==bd_6a9c_dlmb_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_6a9c_dlmb_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_6a9c_dlmb_cntlr_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_6a9c_ilmb_cntlr_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_6a9c_lmb_bram_I_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_6a9c_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6a9c_iomodule_0_0 || ORIG_REF_NAME==bd_6a9c_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_6a9c_iomodule_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/bd_6a9c_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/microblaze_microblaze_mcs_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_mcs_0_0 || ORIG_REF_NAME==microblaze_microblaze_mcs_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_mcs_0_0/microblaze_microblaze_mcs_0_0_ooc.xdc

# XDC: bd/microblaze/microblaze_ooc.xdc
