# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -ruleid {19}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {20}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.cache/wt [current_project]
set_property parent.project_path C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/microblaze.bd
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_6a9c_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_6a9c_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_6a9c_microblaze_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_6a9c_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_6a9c_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_6a9c_rst_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_6a9c_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_6a9c_ilmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_6a9c_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_6a9c_dlmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_6a9c_dlmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_6a9c_ilmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_6a9c_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_6a9c_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_6a9c_iomodule_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/bd_0/bd_6a9c_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/microblaze_microblaze_mcs_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_mcs_0_0/microblaze_microblaze_mcs_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/microblaze_ooc.xdc]
set_property is_locked true [get_files C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/microblaze.bd]

read_verilog -library xil_defaultlib C:/Users/acb610/project_1/project_1.srcs/sources_1/new/gomoku.v
read_vhdl -library xil_defaultlib C:/Users/acb610/Documents/GitHub/CS2204-Summer-2016-Research-Project/microblaze_project/microblaze_project.srcs/sources_1/bd/microblaze/hdl/microblaze_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/acb610/Downloads/nexys4ddr_master_xdc/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/acb610/Downloads/nexys4ddr_master_xdc/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top microblaze_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef microblaze_wrapper.dcp

catch { report_utilization -file microblaze_wrapper_utilization_synth.rpt -pb microblaze_wrapper_utilization_synth.pb }
